version: 2.1
workflows:
  jobs:
    build:
      docker:
        - image: gcc:8.1.0
      working_directory: ~/work
      steps:
        - checkout
        - run: make
  	      path: /home/build
  	    - store_artifacts
