version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run: 
          name: Build step for C code
          command: |
             gc giggle.c -o giggle.out
             echo "STDERR: $stderr"
      - run: 
          name: Running out file and Store the ouput to html file
          command: |
             ./giggle.out
             rm index.html
             echo "<div class="text">" > index.html
             echo "<pre>" >> index.html
             echo -e "CI-BRANCH:$CIRCLE_BRANCH" >> index.html
             echo -e "CI-BUILD_NUM:$CIRCLE_BUILD_NUM" >> index.html
             ./giggle.out >> index.html
             echo "</pre>" >> index.html
             echo "</div>" >> index.html
             git config --global user.email "kishorekumar015@gmail.com"
             git config --global user.name "kkumarta"
             git clone https://github.com/kkumarta/demo-giggle.git
             git config --global user.email "kishorekumar015@gmail.com"
             git config --global user.name "kkumarta"
             rm demo-giggle/docs/index.html
             cp index.html demo-giggle/docs/index.html
             cd demo-giggle/docs
             git add index.html
             git commit -m " report for build output [skip ci]"
             git push
      - store_artifacts:
          path: ~/work/giggle.out
          destination: /home/artifact
      - store_artifacts:
          path: ~/work/_config.yml
          destination: /home/artifact
