version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run: gcc giggle.c -o giggle.out
      - run: 
          name: Running out file
          command: |
             ./giggle.out
      - store_artifacts:
          path: ~/work/giggle.out
          destination: /home/artifact
