version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run: gcc giggle.c
      - store_artifacts:
          path: /home/build
