version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run: 
          name: Build step for C code
          command: |
             
             echo "export test_var="Build-Phase"" >> $BASH_ENV
             gcc giggle.c -o giggle.out | tee ~/output.log
            
      - run: 
          name: Running out file and Store the ouput to html file
          
          command: |
             echo "export test_var="compile-Phase"" >> $BASH_ENV
             ./giggle.out 
             rm index.html
             echo "<div class="text">" > index.html
             echo "<pre>" >> index.html
             echo -e "CI-BRANCH:$CIRCLE_BRANCH" >> index.html
             echo -e "CI-BUILD_NUM:$CIRCLE_BUILD_NUM" >> index.html
             echo -e "\e]8;;BuildURL:$CIRCLE_BUILD_URL\e]8;;\a" >> index.html
             ./giggle.out >> index.html 
             echo "</pre>" >> index.html
             echo "</div>" >> index.html
             git config --global user.email "kishorekumar015@gmail.com"
             git config --global user.name "kkumarta"
             git clone https://github.com/kkumarta/demo-giggle.git
             git config --global user.email "kishorekumar015@gmail.com"
             git config --global user.name "kkumarta"
             rm demo-giggle/docs/index.html
             cp index.html demo-giggle/docs/index.html
             cd demo-giggle/docs
             git add index.html
             git commit -m " report for build output [skip ci]"
             git push
      - run:
          name: Sending failure message to GH Page
          command: |
             echo $test_var
             if [ -z "$test_var" ]
             then
                  export test_var="checkout-Phase"
                  echo $test_var
             fi
             rm index.html
             echo "<div class="text">" > index.html
             echo "<pre>" >> index.html
             echo -e "CI-BRANCH:$CIRCLE_BRANCH" >> index.html
             echo -e "CI-BUILD_NUM:$CIRCLE_BUILD_NUM" >> index.html
             echo -e "Build Failed" >> index.html
             echo -e "BuildSTEP:$test_var" >> index.html
             #echo -e "BuildURL:$CIRCLE_BUILD_URL" >> index.html
             echo -e "\e]8;;BuildURL:$CIRCLE_BUILD_URL\e]8;;\a" >> index.html
             echo "</pre>" >> index.html
             echo "</div>" >> index.html
             git config --global user.email "kishorekumar015@gmail.com"
             git config --global user.name "kkumarta"
             git clone https://github.com/kkumarta/demo-giggle.git
             git config --global user.email "kishorekumar015@gmail.com"
             git config --global user.name "kkumarta"
             rm demo-giggle/docs/index.html
             cp index.html demo-giggle/docs/index.html
             cd demo-giggle/docs
             git add index.html
             git commit -m " report for build output [skip ci]"
             git push
          when: on_fail
      - store_artifacts:
          path: ~/work/giggle.out
          destination: /home/artifact
      - store_artifacts:
          path: ~/work/demo-giggle/docs/index.html
          destination: /home/artifact/html
