version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run: 
          name: Build step for C code
          command: |
             gcc giggle.c -o giggle.out
      - run: 
          name: Running out file and Store the ouput to text file
          command: |
             ./giggle.out
             ./giggle.out > _config.yml
             git config user.email "kishorekumar015@gmail.com"
             git config user.name "kkumarta"
             git add _config.yml
             git commit -m " report for build output"
             git push
      - store_artifacts:
          path: ~/work/giggle.out
          destination: /home/artifact
      - store_artifacts:
          path: ~/work/_config.yml
          destination: /home/artifact
